name:                nasHSpar
version:             0.1.0.0
github:              "githubuser/nasHSpar"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/nasHS#readme>

dependencies:
- base >= 4.7 && < 14
- vector 
- monad-par 
- monad-par-extras
- abstract-par 
- pcg-random 
- parallel
- clock 
- transformers
- primitive 
- sparse-linear-algebra
- deepseq 
- ghc-prim

# library:
#   source-dirs: src

executables:
  is:
    main:                is.hs
    source-dirs:         src 
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -fllvm
    - -optlo-O3
    dependencies:
    - vector
    - pcg-random 
    - parallel 
    - clock 
  is-monad-par:
    main:                is-par-monad.hs
    other-modules: 
    - Patterns 
    - PVector 
    - ParStreams 
    - SparseData 
    source-dirs:         src 
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -fllvm
    - -optlo-O3
    - -eventlog 
    - -funfolding-use-threshold=16
    dependencies:
    - vector
    - pcg-random 
    - monad-par 
    - abstract-par 
    - monad-par-extras
    - primitive 
    - transformers 
    - clock
    - deepseq 
  combina-test:
    main:           combinatorTest.hs
    other-modules: 
    - Patterns 
    - SparseData 
    source-dirs:         src 
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -fllvm
    - -optlo-O3
    - -eventlog 
    - -funfolding-use-threshold=16
    dependencies:
    - vector
    - pcg-random 
    - monad-par 
    - abstract-par 
    - monad-par-extras
    - primitive 
    - transformers 
    - clock
    - deepseq 
  ep:
    main:                ep.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -fllvm
    - -optlo-O3
    dependencies:
    - vector
    - pcg-random
    - primitive
    - MonadRandom
    - random 
    - mtl 
    - containers
    - parallel 
  # cg:
  #   main:                cg.hs
  #   source-dirs:         src
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -O2
  #   - -fllvm
  #   - -optlo-O3
  #   dependencies:
  #   - pcg-random
  #   - sparse-linear-algebra 
  #   - vector 
  #   - deepseq
#   patterns:
#     # main: Patterns.hs 
#     exposed-modules: Patter
#     source-dirs: src
#     dependencies:
#     - monad-par 
#     - abstract-par 
#     - monad-par-extras
#     - vector 

